-- NOTE: Order matters
require("plugin_config.colourscheme")
require("plugin_config.lualine")
require("plugin_config.gitsigns")
require("plugin_config.lazygit")
require("plugin_config.telescope")
require("plugin_config.oil")
require("plugin_config.treesitter")
require("plugin_config.blink")
require("plugin_config.lazydev")
require("plugin_config.lsp")
require("plugin_config.ibl")
