-- Quick switch to favourite apps with cmd+<N>
hs.hotkey.bind({ "cmd" }, "1", function()
	hs.application.launchOrFocus("Firefox")
end)
hs.hotkey.bind({ "cmd" }, "2", function()
	hs.application.launchOrFocus("Alacritty")
end)
hs.hotkey.bind({ "cmd" }, "3", function()
	hs.application.launchOrFocus("Obsidian")
end)
hs.hotkey.bind({ "cmd" }, "4", function()
	hs.application.launchOrFocus("Calendar")
end)
hs.hotkey.bind({ "cmd" }, "5", function()
	hs.application.launchOrFocus("Spotify.app")
end)
