# https://alacritty.org/config-alacritty.html

[env]
term = "xterm-256color"

[font]
size = 16

[font.normal]
family = "Menlo" # Alacritty default on macOS
# family = "UbuntuMono Nerd Font"

[window]
# decorations = "Full" | "None" | "Transparent" | "Buttonless"
decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_title = true

[window.padding]
x = 10
y = 10

[mouse]
hide_when_typing = true

