# Adapted from https://github.com/mischavandenburg/dotfiles

[font]
size = 16

[font.normal]
family = "Menlo" # Alacritty default on macOS
# family = "UbuntuMono Nerd Font"

[window]
decorations = "None"
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5



