#!/usr/bin/env bash

echo "TODO: currently in --dry-run. You need to test it!"

source ~/.config/.extra # Get drive paths
for DRIVE in $BACKUP_HDD_01 $BACKUP_HDD_02; do
	if ! [[ -n $DRIVE ]]; then
		echo "Backup drives not properly specified in ~/.config/.extra"
		exit 0
	fi
	if ! [[ -e "$DRIVE" && -d "$DRIVE" ]]; then
		echo "$DRIVE not found, skipping."
		continue
	fi
	echo -e "\nSyncing '$DRIVE'...\n"
	(set -x; rsync -avh --exclude '.DS_Store' $HOME/1-Projects/ "$DRIVE"/1-Projects/ --dry-run)
	(set -x; rsync -avh --exclude '.DS_Store' $HOME/2-Areas/ "$DRIVE"/2-Areas/ --dry-run)
	(set -x; rsync -avh --exclude '.DS_Store' $HOME/3-Resources/ "$DRIVE"/3-Resources/ --dry-run)
	(set -x; rsync -avh --exclude '.DS_Store' $HOME/4-Archives/ "$DRIVE"/4-Archives/ --dry-run)
	echo -e "\nFinished syncing to '$DRIVE'\n"
done
