#!/usr/bin/env bash

# source ~/.config/.extra # Pull in the value of MAIN_OBSIDIAN_VAULT
if ! [[ -n $MAIN_OBSIDIAN_VAULT && -e "$MAIN_OBSIDIAN_VAULT" ]]; then
	echo "MAIN_OBSIDIAN_VAULT not defined in ~/.config/.extra or path is invalid."
	exit 0
fi
GIT_VAULT="$HOME/3-Resources/Obsidian-vaults/TheVault/"
TRASH="$HOME/.Trash"
TRASHDIR="$TRASH/$(date +%Y-%m-%d_%H-%M-%S)"

echo "Creating new directory: $TRASHDIR"
mkdir "$TRASHDIR"

echo "Clearing '$GIT_VAULT'..."
for item in "$GIT_VAULT"/*; do
	if [[ "$item" == ".git" || "$item" == ".gitignore" ]]; then
		echo "Ignoring $item"
		continue
	fi
	echo "Trashing $item"
	mv -- "$item" "$TRASHDIR"
done

# echo "Clearing .obsidian/ and .trash/ to $TRASHDIR"
(set -x; mv -- "$GIT_VAULT/.obsidian/" "$TRASHDIR")
(set -x; mv -- "$GIT_VAULT/.trash/" "$TRASHDIR")

echo "Syncing from '$MAIN_OBSIDIAN_VAULT'..."
(set -x; rsync -ah --exclude '.DS_Store' "$MAIN_OBSIDIAN_VAULT" "$GIT_VAULT")

