#!/usr/bin/env bash
# Version 2.1

if ! [[ -n $LOGDIR ]]; then
	LOGDIR="$HOME/3-Resources/Logs"
	echo -e "LOGDIR not set. Creating at '$LOGDIR'"
fi
mkdir -p "$LOGDIR"
LOGFILE="$LOGDIR/$(date +%Y-%m-%d_%H-%M-%S)_gt-synchdd.log"
SUBDIRS_TO_SYNC=(
	"0-Inbox" \
	"1-Projects" \
	"2-Areas" \
	"3-Resources" \
	"4-Archives" \
)

# TODO DEBUGGING...
# TEST_PATH_01="$HOME/Desktop/test01"
# TEST_PATH_02="$HOME/Desktop/test02"
# for DRIVE in $TEST_PATH_01 $TEST_PATH_02; do
for DRIVE in $BACKUP_HDD_01 $BACKUP_HDD_02; do
	if ! [[ -n $DRIVE ]]; then
		echo -e "Backup drives not properly specified. Check ~/.config/.extra"
		exit 1 # Exit code 1 for error
	fi
	if ! [[ -e "$DRIVE" && -d "$DRIVE" ]]; then
		echo -e "\n$DRIVE not found, skipping.\n"
		continue
	fi
	echo -e "\n\nSyncing '$DRIVE'...\n"
	for SUBDIR in "${SUBDIRS_TO_SYNC[@]}"; do
		(set -x; rsync -avh \
			--backup \
			--backup-dir="$DRIVE/Deleted/$(date +%Y-%m-%d_%H-%M-%S)" \
			--delete-after \
			--stats \
			--progress \
			--log-file="$LOGFILE" \
			--exclude='.DS_Store' \
			--exclude='.DocumentRevisions-V100' \
			--exclude='.Spotlight-V100' \
			--exclude='.TemporaryItems' \
			--exclude='.Trashes' \
			--exclude='._*' \
			--exclude='.fseventsd' \
			--exclude='.timemachine' \
			"$HOME/$SUBDIR/" "$DRIVE/$SUBDIR/" \
		)
	done
	echo -e "\nFinished syncing to '$DRIVE'\n"
done

echo -e "\nLogs written to '$LOGFILE'\n"
